import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { useGame } from '../GameContext'
import { BackButton } from '../components/BackButton'
import memoryBackground from '../../assets/round2/memories/round2-memory-bg.png'
import lacHong from '../../assets/round2/memories/cards/memory-lac-hong.png'
import miNuong from '../../assets/round2/memories/cards/memory-mi-nuong.png'
import phuDong from '../../assets/round2/memories/cards/memory-phu-dong.png'
import coLoa from '../../assets/round2/memories/cards/memory-co-loa.png'
import coLoaMap from '../../assets/round2/coloa/round2-co-loa-map.png'
type MemoryId = 'lac-hong' | 'mi-nuong' | 'phu-dong' | 'co-loa'
type MarkerId = 'wall' | 'gate' | 'moat' | 'arrow' | 'village'
type Phase = 'ROUND2_ENTER'|'MEMORY_INTRO'|'MEMORY_PLAYING'|'MEMORY_VALIDATING'|'MEMORY_WRONG'|'MEMORY_COMPLETE'|'COLOA_INTERSTITIAL_ENTER'|'COLOA_INTERSTITIAL_READY'|'COLOA_MAP_ENTERING'|'COLOA_PLAYING'|'COLOA_WRONG'|'COLOA_CORRECT'
type SuccessStage = 'idle'|'correct-selected'|'anticipation'|'outer'|'middle'|'inner'|'fortress-complete'|'success-message'
const memories = [{id:'lac-hong' as MemoryId,image:lacHong,position:'50% 50%'},{id:'mi-nuong' as MemoryId,image:miNuong,position:'50% 48%'},{id:'phu-dong' as MemoryId,image:phuDong,position:'50% 45%'},{id:'co-loa' as MemoryId,image:coLoa,position:'50% 50%'}]
const answerOrder: MemoryId[]=['lac-hong','mi-nuong','phu-dong','co-loa']
const markers:Array<{id:MarkerId;x:number;y:number;delay:string}>=[{id:'wall',x:.705,y:.685,delay:'-.1s'},{id:'gate',x:.303,y:.575,delay:'-.6s'},{id:'moat',x:.232,y:.755,delay:'-1.1s'},{id:'arrow',x:.532,y:.302,delay:'-1.55s'},{id:'village',x:.805,y:.435,delay:'-2s'}]
const wallSegments={
 outer:['M403 360 C490 277 620 241 734 240 C902 236 1080 281 1216 337 C1280 365 1323 402 1352 441','M1355 460 C1396 520 1390 580 1345 638 C1308 688 1240 716 1168 731','M1100 735 C980 750 846 724 730 694 C630 669 530 636 470 582','M430 542 C390 487 382 421 403 360'],
 middle:['M500 385 C544 345 604 318 671 303 C760 285 859 296 935 321 C1008 345 1072 382 1115 431','M1110 446 C1140 495 1120 538 1068 570','M1015 584 C920 614 823 621 730 602 C650 585 578 548 534 500','M524 480 C495 443 489 412 500 385'],
 inner:['M657 432 C717 399 797 390 864 406 C925 422 971 455 995 492','M998 508 C1008 545 972 568 925 582','M887 591 C818 604 751 592 700 565','M681 548 C650 520 645 468 657 432']
}
export function MemoryGameScene(){
 const {dispatch}=useGame();const [phase,setPhase]=useState<Phase>('ROUND2_ENTER');const [order,setOrder]=useState<MemoryId[]>(['phu-dong','lac-hong','co-loa','mi-nuong']);const [dragged,setDragged]=useState<MemoryId|null>(null);const [over,setOver]=useState<MemoryId|null>(null);const [feedback,setFeedback]=useState('');const [selected,setSelected]=useState<MarkerId|null>(null);const [memoryStep,setMemoryStep]=useState(0);const [memoryLink,setMemoryLink]=useState(0);const [memoryMessage,setMemoryMessage]=useState(false);const [successStage,setSuccessStage]=useState<SuccessStage>('idle');const [wallLevel,setWallLevel]=useState(0);const [showSuccess,setShowSuccess]=useState(false);const timers=useRef<number[]>([]);const successStarted=useRef(false);const debug=import.meta.env.DEV;
 const later=(fn:()=>void,ms:number)=>timers.current.push(window.setTimeout(fn,ms));const log=(stage:string)=>{if(debug)console.info('[Coloa] '+stage)}
 useEffect(()=>{[memoryBackground,lacHong,miNuong,phuDong,coLoa,coLoaMap].forEach(src=>{const image=new Image();image.src=src;void image.decode?.().catch(()=>undefined)});later(()=>setPhase('MEMORY_INTRO'),500);later(()=>setPhase('MEMORY_PLAYING'),1300);return()=>timers.current.forEach(window.clearTimeout)},[])
 const reorder=(from:MemoryId,to:MemoryId)=>setOrder(current=>{const next=[...current];next.splice(next.indexOf(from),1);next.splice(next.indexOf(to),0,from);return next})
 const confirm=()=>{if(phase!=='MEMORY_PLAYING')return;setPhase('MEMORY_VALIDATING');if(order.every((id,i)=>id===answerOrder[i])){setPhase('MEMORY_COMPLETE');later(()=>setMemoryStep(1),180);later(()=>setMemoryLink(1),520);later(()=>setMemoryStep(2),780);later(()=>setMemoryLink(2),1120);later(()=>setMemoryStep(3),1380);later(()=>setMemoryLink(3),1720);later(()=>setMemoryStep(4),1980);later(()=>setMemoryMessage(true),2700);later(()=>setPhase('COLOA_INTERSTITIAL_ENTER'),3900);later(()=>setPhase('COLOA_INTERSTITIAL_READY'),4780)}else{setFeedback('Dòng ký ức vẫn chưa liền mạch...');later(()=>setPhase('MEMORY_WRONG'),70);later(()=>{setFeedback('');setPhase('MEMORY_PLAYING')},1650)}}
 const startSuccess=()=>{setPhase('COLOA_CORRECT');setSuccessStage('correct-selected');log('correct selected');later(()=>{setSuccessStage('anticipation');log('anticipation')},150);later(()=>{setWallLevel(1);setSuccessStage('outer');log('outer reveal')},250);later(()=>{setShowSuccess(true);log('success message')},320);later(()=>{setWallLevel(2);setSuccessStage('middle');log('middle reveal')},900);later(()=>{setWallLevel(3);setSuccessStage('inner');log('inner reveal')},1650);later(()=>{setSuccessStage('fortress-complete');log('fortress complete')},2950);later(()=>{log('reward');dispatch({type:'COMPLETE_ROUND_TWO'})},4050)}
 const select=(id:MarkerId)=>{if(phase!=='COLOA_PLAYING'||successStarted.current)return;setSelected(id);if(id!=='wall'){setFeedback('Dấu vết này chưa khớp.');setPhase('COLOA_WRONG');later(()=>{setFeedback('');setSelected(null);setPhase('COLOA_PLAYING')},1450);return}successStarted.current=true;setFeedback('Các vòng thành bao bọc nhiều lớp, tạo nên hệ thống phòng thủ đặc trưng của Cổ Loa.');startSuccess()}
 const down=(event:PointerEvent<HTMLButtonElement>,id:MemoryId)=>{if(phase==='MEMORY_PLAYING'){event.currentTarget.setPointerCapture(event.pointerId);setDragged(id)}};const up=(event:PointerEvent<HTMLButtonElement>)=>{const to=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLButtonElement>('[data-memory-id]')?.dataset.memoryId as MemoryId|undefined;if(dragged&&to&&dragged!==to)reorder(dragged,to);setDragged(null);setOver(null)}
 const interstitial=phase==='COLOA_INTERSTITIAL_ENTER'||phase==='COLOA_INTERSTITIAL_READY';const map=phase==='COLOA_MAP_ENTERING'||phase==='COLOA_PLAYING'||phase==='COLOA_WRONG'||phase==='COLOA_CORRECT';const search=new URLSearchParams(window.location.search);const alignmentDebug=debug&&(search.get('debug-coloa')==='true'||search.get('debug-coloa-wall')==='true')
 return <section className={'round2-chapter phase-'+phase+' success-'+successStage+' wall-level-'+wallLevel+' success-copy-'+(showSuccess?'on':'off')+' memory-step-'+memoryStep+' memory-link-'+memoryLink+' memory-message-'+(memoryMessage?'on':'off')}><BackButton onClick={()=>phase==='MEMORY_PLAYING'&&dispatch({type:'RETURN_TO_CHAPTER'})}/><div className="round2-dust"/><div className="memory-world" style={{backgroundImage:'url('+memoryBackground+')'}}/>
 <section className="memory-chapter" aria-hidden={interstitial||map}><header className="round2-title"><p>ROUND II</p><h1>XẾP LẠI KÝ ỨC</h1><span>Khôi phục dòng ký ức đã thất lạc.</span></header><div className="memory-composition"><div className="memory-timeline">{answerOrder.map((id,i)=><div className={'timeline-stop '+(i<memoryStep?'lit ':'')+(i<memoryLink?'energy-link':'')} key={id}><b>0{i+1}</b></div>)}</div><div className="memory-row">{order.map((id,i)=>{const memory=memories.find(item=>item.id===id)!;return <button data-memory-id={id} key={id} className={'memory-card '+(i<memoryStep?'is-restored ':'')+(i===memoryStep-1?'is-restoring ':'')+(dragged===id?'is-dragged ':'')+(over===id?'is-over':'')} onPointerDown={e=>down(e,id)} onPointerEnter={()=>dragged&&setOver(id)} onPointerUp={up} onPointerCancel={()=>setDragged(null)}><img src={memory.image} alt="" draggable={false} style={{objectPosition:memory.position}}/><span/></button>})}</div><div className="memory-status memory-restored-message" aria-live="polite"><b>{memoryMessage?'DÒNG KÝ ỨC ĐÃ ĐƯỢC KHÔI PHỤC':feedback}</b>{feedback&&<span>Hãy thử quan sát lại thứ tự của những câu chuyện.</span>}</div><button className="game-button memory-confirm" disabled={phase!=='MEMORY_PLAYING'} onClick={confirm}>XÁC NHẬN KÝ ỨC</button></div></section>
 <section className="coloa-interstitial" aria-hidden={!interstitial}><div className="interstitial-fog fog-back"/><div className="interstitial-fog fog-mid"/><div className="interstitial-fog fog-front"/><div className="interstitial-copy"><p>MẢNH KÝ ỨC II</p><h1>GIẢI MÃ CỔ LOA</h1><span>Ký ức cuối cùng dẫn đến một thành trì cổ xưa.<br/>Giữa những vòng thành và hào nước, một dấu vết vẫn đang chờ được tìm thấy.</span><button className="coloa-start" disabled={phase!=='COLOA_INTERSTITIAL_READY'} onClick={()=>{if(phase==='COLOA_INTERSTITIAL_READY'){setPhase('COLOA_MAP_ENTERING');later(()=>setPhase('COLOA_PLAYING'),1080)}}}>BẮT ĐẦU GIẢI MÃ</button></div></section>
 <section className="coloa-world" aria-hidden={!map}><div className="coloa-map-viewport"><div className="coloa-map-canvas"><img className="coloa-map-art" src={coLoaMap} alt="Bản đồ thành Cổ Loa"/><svg className={'wall-segment-trace '+(alignmentDebug?'is-debug':'')} viewBox="0 0 1536 1024" aria-hidden="true">{Object.entries(wallSegments).map(([group,segments])=><g key={group} className={'wall-group '+group}>{segments.map((d,index)=><g className="wall-segment" key={d}><path className="wall-glow" pathLength="1" d={d}/><path className="wall-core" pathLength="1" d={d}/>{index===segments.length-1&&<circle className="wall-head" r="4"/>}</g>)}</g>)}</svg><div className="marker-overlay">{markers.map(marker=><button key={marker.id} disabled={phase!=='COLOA_PLAYING'} onClick={()=>select(marker.id)} className={'map-marker marker-'+marker.id+' '+(selected===marker.id?'is-selected':'')} style={{left:String(marker.x*100)+'%',top:String(marker.y*100)+'%','--pulse-delay':marker.delay} as React.CSSProperties}><i/><span/></button>)}</div>{alignmentDebug&&<div className="coloa-debug">1536 × 1024 shared canvas</div>}</div></div><div className="map-fog"/><div className="coloa-vignette"/><aside className="coloa-clue" aria-live="polite"><b>MANH MỐI</b><p>“Bộ phận được dựng theo cấu trúc dạng xoáy trôn ốc, dùng để bao che không gian bên trong hoặc chống đỡ tiến công của địch.”</p><strong>Hãy chọn vị trí tương ứng trên Cổ Loa.</strong></aside>{phase==='COLOA_WRONG'&&<div className="marker-feedback">{feedback}</div>}{showSuccess&&<div className="wall-answer"><b>CHÍNH XÁC</b><strong>VÒNG THÀNH CỔ LOA</strong><span>{feedback}</span></div>}</section></section>
}
